extends: default
ignore: |
  ./rtv/**
  ./clusters/prod/flux-system/**
  ./**/*.sops.yaml
  rtv/**
  clusters/prod/flux-system/**
  **/*.sops.yaml
rules:
  line-length: disable
  document-start: disable
  truthy: disable
  comments:
    min-spaces-from-content: 1
  indentation:
    indent-sequences: true
    spaces: 2
