apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lan-vips
spec:
  serviceSelector:
    matchExpressions:
      - key: io.kubernetes.service.namespace
        operator: In
        values:
          - kube-system
      - key: io.kubernetes.service.name
        operator: In
        values:
          - traefik
          - traefik-internal
  loadBalancerIPs: true
