apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lan-vips
  labels:
    app.kubernetes.io/name: lan-vips
    app.kubernetes.io/instance: lan-vips-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  serviceSelector:
    matchExpressions:
      - key: io.kubernetes.service.namespace
        operator: In
        values:
          - kube-system
      - key: io.kubernetes.service.name
        operator: In
        values:
          - traefik
          - traefik-internal
  loadBalancerIPs: true
