apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cilium
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 10m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    kubeProxyReplacement: true
    k8sServiceHost: 10.10.20.42
    k8sServicePort: 6443
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.42.0.0/16
        clusterPoolIPv4MaskSize: 24
    l2announcements:
      enabled: true
    k8sClientRateLimit:
      qps: 20
      burst: 40
