apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cilium
    app.kubernetes.io/instance: cilium-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  interval: 1h
  url: https://helm.cilium.io
