apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: external-dns
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"
    services: "10"
    configmaps: "50"
    secrets: "50"
    persistentvolumeclaims: "5"
