apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: external-dns
  labels:
    app.kubernetes.io/name: namespace-quota
    app.kubernetes.io/instance: namespace-quota-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"
    services: "10"
    configmaps: "50"
    secrets: "50"
    persistentvolumeclaims: "5"
