apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: external-dns
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
