apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-hygiene
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-hygiene
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-hygiene
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-hygiene
subjects:
  - kind: ServiceAccount
    name: node-hygiene
    namespace: kube-system
