apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  interval: 10m
  chart:
    spec:
      chart: trivy-operator
      version: 0.32.0
      sourceRef:
        kind: HelmRepository
        name: aquasecurity
        namespace: trivy-system
      interval: 10m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    operator:
      vulnerabilityReportsEnabled: true
      scannerReportTTL: "6h"
      builtInTrivyServer: true
      scanJobsConcurrentLimit: 5
    trivyOperator:
      skipInitContainers: true
    trivy:
      ignoreUnfixed: true
