apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: trivy-system
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
    services: "10"
    configmaps: "50"
    secrets: "50"
    persistentvolumeclaims: "5"
