apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: trivy-system
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      default:
        cpu: "1"
        memory: 1Gi
