apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:sdn/ZiDa0hMlkuUrxx4xYxbzPY2q8W7WijCZpUhfuf6jm58AnO2KlxYsx/ioQHABegLJmpK6PfYG2h63YZCiZwPCF0QTBUjoEix3CCqnJLveBHQbNYPJ6n68sq4TIvC96Pv1nA+h9w6NEr16/VR9PdDtkq5oxgQTNhnBRDNlvhDf+YbQNaY3YNee2oIYpTPUC7+gs2MRWpNl7TrUhBpNpDChJwMDkITio2WDGgQB62Ag54arZr2LcmPCQNfrX74VuFf4XEoNMuHoP24Eb2FFSz59w2iwq02XIcxn57w+CFP52aOcOfLtr4btwukmoo/IpSFqWWXRIsc=,iv:UHxH2YoE73e/XuFhL09gt/ZFJOfkExHHSd9mmga3bTs=,tag:ZhKLeAM4VwqseUGbCtduGA==,type:str]
sops:
    age:
        - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseVVNcmpxcG5NaGQ3bmxV
            akNTZUVLc0d0U2oxdGdwMjZWaHM1bzVYcFZvCjVOeVZmTmJzWXFESlgyV3F0d1VC
            MGtPMFFTZGMzTHM0T3BNSWNMR1NJU3cKLS0tIE14UTVDWElCdGZsWC83TDBITzRo
            VGVDd1FDRmhCYmdWWmdrTEJhcm1XR2cKFJvFApmtULIAVhxJEPsV0jU3sgNHGHhP
            tfvc+WziU14p0TpeLmzVpt/3ZpxEAFZSNiZvPHbgq4K7CZ024vlx8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T15:16:31Z"
    mac: ENC[AES256_GCM,data:0SC18AyQJ7JdScsr++jG66fJvDCtpy1l2ylkswmIuIQuMgChisP3Pf/REr31Ei3WW4p1HKqS1IJQuPF6ZkTDc5slMfLy1I6ELMn0tXPlfYtuQ9o55ASwQplv6+O74JhHK8OMeFxJcridk6Jt/L/LqdqBKl78s+2in+qzwYCDmDk=,iv:t7I9J06LTaO0EC0B6/MurfX+s3M9vNhdOKCeffIJS1M=,tag:dmCamwQSPBzVG8QJ7JrWIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
