apiVersion: v1
kind: Service
metadata:
  name: changedetection
  labels:
    app.kubernetes.io/name: changedetection
    app.kubernetes.io/instance: changedetection-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: changedetection
  ports:
    - name: http
      port: 5000
      targetPort: http
