apiVersion: v1
kind: Service
metadata:
  name: glances
  namespace: monitoring
  labels:
    app.kubernetes.io/name: glances
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: glances
  ports:
    - name: http
      port: 61208
      targetPort: http
