apiVersion: v1
kind: Service
metadata:
  name: karma
  namespace: monitoring
  labels:
    app.kubernetes.io/name: karma
    app.kubernetes.io/instance: karma-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: karma
  ports:
    - name: http
      port: 80
      targetPort: http
