apiVersion: v1
kind: Service
metadata:
  name: karma
  namespace: monitoring
  labels:
    app.kubernetes.io/name: karma
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: karma
  ports:
    - name: http
      port: 80
      targetPort: http
