apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: ntfy
spec:
  selector:
    app.kubernetes.io/name: ntfy
  ports:
    - name: http
      port: 80
      targetPort: http
