apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/instance: ntfy-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  selector:
    app.kubernetes.io/name: ntfy
  ports:
    - name: http
      port: 80
      targetPort: http
