apiVersion: v1
kind: Service
metadata:
  name: playwright-chrome
  labels:
    app.kubernetes.io/name: playwright-chrome
    app.kubernetes.io/instance: playwright-chrome-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: playwright-chrome
  ports:
    - name: http
      port: 3000
      targetPort: http
