apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-autoheal
  namespace: monitoring
  labels:
    app.kubernetes.io/name: pod-autoheal
    app.kubernetes.io/instance: pod-autoheal-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-autoheal
  labels:
    app.kubernetes.io/name: pod-autoheal
    app.kubernetes.io/instance: pod-autoheal-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-autoheal
  labels:
    app.kubernetes.io/name: pod-autoheal
    app.kubernetes.io/instance: pod-autoheal-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-autoheal
subjects:
  - kind: ServiceAccount
    name: pod-autoheal
    namespace: monitoring
