apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-autoheal
  namespace: monitoring
  labels:
    app.kubernetes.io/name: pod-autoheal
    app.kubernetes.io/instance: pod-autoheal-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          serviceAccountName: pod-autoheal
          restartPolicy: OnFailure
          containers:
            - name: autoheal
              image: python:3.12.12-alpine3.22@sha256:848ba4413eb897e225159b8fc1b02094576cbae4aa73fc13142608ae2c8c0e32
              imagePullPolicy: IfNotPresent
              command:
                - python
                - /app/autoheal.py
              resources:
                requests:
                  cpu: 50m
                  memory: 96Mi
                limits:
                  memory: 256Mi
              envFrom:
                - secretRef:
                    name: pod-autoheal-telegram
              volumeMounts:
                - name: app
                  mountPath: /app
          volumes:
            - name: app
              configMap:
                name: pod-autoheal
                defaultMode: 0555
