apiVersion: v1
kind: Service
metadata:
  name: tautulli-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tautulli-exporter
    app.kubernetes.io/instance: tautulli-exporter-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tautulli-exporter
  ports:
    - name: http
      port: 8000
      targetPort: http
