apiVersion: v1
kind: Service
metadata:
  name: tautulli-library-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tautulli-library-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tautulli-library-exporter
  ports:
    - name: http
      port: 9101
      targetPort: http
