apiVersion: v1
kind: Service
metadata:
  name: trivy-fixable-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: trivy-fixable-exporter
spec:
  selector:
    app.kubernetes.io/name: trivy-fixable-exporter
  ports:
    - name: http
      port: 9102
      targetPort: http
