apiVersion: v1
kind: Service
metadata:
  name: trivy-fixable-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: trivy-fixable-exporter
    app.kubernetes.io/instance: trivy-fixable-exporter-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  selector:
    app.kubernetes.io/name: trivy-fixable-exporter
  ports:
    - name: http
      port: 9102
      targetPort: http
