apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-fixable-exporter
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-fixable-exporter
rules:
  - apiGroups:
      - aquasecurity.github.io
    resources:
      - vulnerabilityreports
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-fixable-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-fixable-exporter
subjects:
  - kind: ServiceAccount
    name: trivy-fixable-exporter
    namespace: monitoring
