apiVersion: v1
kind: Service
metadata:
  name: calibre-web
  labels:
    app.kubernetes.io/name: calibre-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: calibre-web
  ports:
    - name: http
      port: 8083
      targetPort: http
