apiVersion: v1
kind: Service
metadata:
  name: calibre-web
  labels:
    app.kubernetes.io/name: calibre-web
    app.kubernetes.io/instance: calibre-web-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: calibre-web
  ports:
    - name: http
      port: 8083
      targetPort: http
