apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: media
  labels:
    app.kubernetes.io/name: default
    app.kubernetes.io/instance: default-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
imagePullSecrets:
  - name: dockerhub-read
