apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-microservices
  labels:
    app.kubernetes.io/name: immich-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-microservices
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-microservices
    spec:
      containers:
        - name: immich-microservices
          image: ghcr.io/immich-app/immich-microservices:release
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: DB_USERNAME
              value: immich
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_PASSWORD
            - name: DB_DATABASE_NAME
              value: immich
            - name: REDIS_HOSTNAME
              value: immich-redis
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: JWT_SECRET
            - name: IMMICH_MACHINE_LEARNING_URL
              value: "http://immich-machine-learning:3003"
          volumeMounts:
            - name: upload
              mountPath: /usr/src/app/upload
              subPath: photos
      volumes:
        - name: upload
          persistentVolumeClaim:
            claimName: media-nfs
