apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  labels:
    app.kubernetes.io/name: immich-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-server
    spec:
      initContainers:
        - name: immich-data-init
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              set -e
              for d in upload thumbs backups library profile encoded-video; do
                mkdir -p "/data/${d}"
                touch "/data/${d}/.immich"
              done
          volumeMounts:
            - name: immich-data
              mountPath: /data
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:release
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 2283
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: DB_USERNAME
              value: immich
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_PASSWORD
            - name: DB_DATABASE_NAME
              value: immich
            - name: REDIS_HOSTNAME
              value: immich-redis
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: JWT_SECRET
            - name: IMMICH_MACHINE_LEARNING_URL
              value: "http://immich-machine-learning:3003"
          volumeMounts:
            - name: immich-data
              mountPath: /data
            - name: media
              mountPath: /mnt/media/photos
              subPath: photos
              readOnly: true
      volumes:
        - name: immich-data
          persistentVolumeClaim:
            claimName: immich-data
        - name: media
          persistentVolumeClaim:
            claimName: media-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  labels:
    app.kubernetes.io/name: immich-server
spec:
  selector:
    app.kubernetes.io/name: immich-server
  ports:
    - name: http
      port: 2283
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int
spec:
  ingressClassName: traefik
  rules:
    - host: photos.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  name: http
    - host: immich.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  name: http
