apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: immich-redirect
  namespace: media
spec:
  redirectRegex:
    regex: ^https?://immich\.romanpeters\.nl/(.*)
    replacement: https://photos.romanpeters.nl/$1
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-redirect-ingress
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int
    traefik.ingress.kubernetes.io/router.middlewares: media-immich-redirect@kubernetescrd,infrastructure-authentik-forward-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: immich.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  name: http
