apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-redis
  labels:
    app.kubernetes.io/name: immich-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-redis
    spec:
      containers:
        - name: redis
          image: redis:8.0.5-alpine3.21
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  labels:
    app.kubernetes.io/name: immich-redis
spec:
  selector:
    app.kubernetes.io/name: immich-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
