apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  labels:
    app.kubernetes.io/name: default-limits
    app.kubernetes.io/instance: default-limits-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      default:
        memory: 24Gi
