apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-nfs-exporter
  namespace: media
  labels:
    app.kubernetes.io/name: media-nfs-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: media-nfs-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: media-nfs-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.8.2
          imagePullPolicy: IfNotPresent
          args:
            - --web.listen-address=:9100
          ports:
            - name: http
              containerPort: 9100
          volumeMounts:
            - name: media
              mountPath: /mnt/media
              readOnly: true
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: media-nfs-exporter
  namespace: media
  labels:
    app.kubernetes.io/name: media-nfs-exporter
spec:
  selector:
    app.kubernetes.io/name: media-nfs-exporter
  ports:
    - name: http
      port: 9100
      targetPort: http
