apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs
  labels:
    app.kubernetes.io/name: media-nfs
    app.kubernetes.io/instance: media-nfs-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.10.10.3
    path: /var/nfs/shared/media
