apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  labels:
    app.kubernetes.io/name: media-nfs
    app.kubernetes.io/instance: media-nfs-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs
  volumeName: media-nfs
