apiVersion: v1
kind: Service
metadata:
  name: overseerr
  labels:
    app.kubernetes.io/name: overseerr
    app.kubernetes.io/instance: overseerr-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: overseerr
  ports:
    - name: http
      port: 5055
      targetPort: http
