apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "20"
    limits.memory: 32Gi
    pods: "50"
    services: "20"
    configmaps: "100"
    secrets: "100"
    persistentvolumeclaims: "20"
