apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
type: Opaque
data:
  DB_PASSWORD: eW91cl9naXRlYV9kYl9wYXNzd29yZA== # Placeholder
  JWT_SECRET: eW91cl9naXRlYV9qd3Rfc2VjcmV0 # Placeholder
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-01-01T00:00:00Z"
  mac: "" # Placeholder
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
