apiVersion: v1
kind: Service
metadata:
  name: playwright-chrome
  labels:
    app.kubernetes.io/name: playwright-chrome
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: playwright-chrome
  ports:
    - name: http
      port: 3000
      targetPort: http
