apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: ClusterIP
  ingress_type: ingress
  ingress_class_name: traefik
  hostname: awx.romanpeters.nl
  redis_image: mirror.gcr.io/library/redis
  redis_image_version: 8.2.4-alpine3.22
  ingress_annotations: |
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int
