apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-data
  labels:
    app.kubernetes.io/name: gitea-postgres-data
    app.kubernetes.io/instance: gitea-postgres-data-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: pvc-ca9e9499-eb87-4aef-97a3-972954a3dddf
  resources:
    requests:
      storage: 10Gi
