apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  labels:
    app.kubernetes.io/name: gitea-data
    app.kubernetes.io/instance: gitea-data-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: pvc-83a04d9d-a596-4fc6-9d45-462f4a129c00
  resources:
    requests:
      storage: 10Gi
