apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.10.10.3
    path: /volume/378ece44-40ef-4052-b45a-3f0185c9478a/.srv/.unifi-drive/media/.data
  mountOptions:
    - nfsvers=4.1
