apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs
  volumeName: media-nfs
