apiVersion: v1
kind: Service
metadata:
  name: garage-webui
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: garage-webui
    app.kubernetes.io/instance: garage-webui-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: garage-webui
  ports:
    - name: http
      port: 3909
      targetPort: http
