apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: garage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: garage
  ports:
    - name: s3
      port: 3900
      targetPort: s3
    - name: rpc
      port: 3901
      targetPort: rpc
    - name: admin
      port: 3903
      targetPort: admin
