apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: infrastructure
spec:
  interval: 10m0s
  chart:
    spec:
      chart: authentik
      version: 2025.12.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: infrastructure
      interval: 10m0s
  values:
    global:
      env: []
    server:
      env: []
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - auth.romanpeters.nl
    postgresql:
      enabled: true
    redis:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: values.yaml
