apiVersion: ENC[AES256_GCM,data:9Mg=,iv:1wN5+979Z3YHmthHgJj+fU8H1Wer1cwScsL7zZEd6I4=,tag:9xCGmN1Ug7QBzzEcJ1/YtA==,type:str]
kind: ENC[AES256_GCM,data:9g2binff,iv:5i5ymD2w+H/H7yLIzqy3LFomnhY44salEGolPZKhQmo=,tag:nAWgrIwJ0GEOyNiCDOEFKQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:7w1OPqMq0MyVOloOErVuRA==,iv:haBGlVHxE/aFhz0uo/zlxMc7L1djZQivUztRGp/r0OA=,tag:/AI6rGtk9j0g6pLFkOIdZw==,type:str]
  namespace: ENC[AES256_GCM,data:ofZivTPxX3Cs4aBcBQs=,iv:ZTmR1GeiHyU4g1TuweJBvpV5K5jUQaLT2Pf/7UaqGIw=,tag:dY6s04K6/2r6pMkNabZ96g==,type:str]
type: ENC[AES256_GCM,data:dJJ8/zNH,iv:2AkemGQLE36OBk5rRPGIEr84tJL7dJGUj2gVeNO4de4=,tag:FpBZIhL3Hkh4SSi+CaGQzw==,type:str]
stringData:
  HOMEPAGE_VAR_AUTHENTIK_API_KEY: ENC[AES256_GCM,data:4NEfimvHTkNaJPIdvDagM+y4o0j1KjjaD3RZEeobSYIGNH8jEiMr2CtSd9qsMlly13DnXwQK6xzaIEIK,iv:84S0liSmRPkdOMt/wpH5lPXZ00kt2nWvT7HZ3NDzWDA=,tag:oCVdXVts4l6sDCKtKKx7nw==,type:str]
  HOMEPAGE_VAR_CHANGEDETECTION_API_KEY: ENC[AES256_GCM,data:EuuqwSCkl17T+OACAgia40PNQi7kmqzUYl9YBYhjqIE=,iv:xKbGBVF+B7gBFK7ZYw27liI1AVu5x2w+FtsfvdDplKc=,tag:p37tP4g1q/Z0trSMWyTXXQ==,type:str]
  HOMEPAGE_VAR_AUDIOBOOKSHELF_API_KEY: ENC[AES256_GCM,data:aaZfMrNiOMUDV1GWEopMmgRkcFBTsRRLt97apIbIkzsjlNb3rLm8RWzNehgw5IbFLy41ZF6uqYmlZUKHMfRbx1dJ/5PLzAixCn+bfCC1rLq44WQl4/2eQP9TmvLY9P0bHilTUtFM2rF5LrH/bucIfAiZjWyw/51aa+aO8WNoZdWxyTxVM28mGd+uUsvwUQp2aiKIWhe1sVzoLahZ1aniSPqSfd+IkN/jEVV24crEr2KaN9TF5kSHDgyS7sCCKFXw4hNy/BZ/g98OIShZk+BeqQ==,iv:U5kRLKRCWQ1f3/bjTAzuR3GuICAeRHlDcKtSavJNZOI=,tag:HPRwtIJIszkGSVNuRovc9A==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWm9UOU5vY0dZVGVSMFpD
        bHprVXNYUElqWXFsR2htQWh0ck11SVpQUHdrClhYNXFscG8xWGkxMExLQVoyMVhD
        MXpZRHIzeDJ4QTRFc1JIL2E3T21EakkKLS0tIGYvMUFQa0dEbnVDNFVJUkdZRUpu
        bGVHZys5RURxVjJpSHRLZ3pyY25Ob2cKhhgorJFX0XYcKxMcUzZthsgVOhX/C1VF
        GVqKtiVbwwpt8T6QJxMJC6DMDad3anNgp3B5t/rTzFsBhX2E1rbueQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T10:56:30Z"
  mac: ENC[AES256_GCM,data:tE6Xvp50vsZZ8TcYO+EM8ORmYIT80y/tGPrsV9tR6cJYi5Yxp4cZtTO0BqNAKh1ABBwpRK+GLQetuEVop1u1EQYAv824Jav5IaiSU1XXBDvhBXGls+OeCF27wwkJKMDKZbFF/Kcg69g1BSV6FvmVzDpvvgrq6BlwyQpnrPIlABA=,iv:wyFqkXzEKhV3Yl0V6nusf+NSyErcdLsiwuzS+NQilyE=,tag:7q9jGfYCt84xGzyyy3IpQA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
