apiVersion: v1
kind: Secret
metadata:
  name: homepage-secrets
  namespace: infrastructure
type: Opaque
stringData:
  HOMEPAGE_VAR_AUTHENTIK_API_KEY: ENC[AES256_GCM,data:cTQjEfbU1A1FWv2cS4X2g1jtleI+txE09Ob6hZhhiSnnqLRCKqu4bzxhlyfIC+ybOyuu1lcK5Dd37rcy,iv:ydyfc9tsVhoRcJVHkg1f/KahdoUp1n4860te1mrED2w=,tag:ps8NrVT8WgmI3Jry/ZpoQA==,type:str]
  HOMEPAGE_VAR_CHANGEDETECTION_API_KEY: ENC[AES256_GCM,data:2MdobnYIp5u2xX8YCU9Y159DYpJ5f8t/epxy3N+ClC0=,iv:8FckfJd3XGgys1RHhuX1RpnM9jl/VLYUj6OWCM2RD0w=,tag:r+fOLz94Ug8d8nJpuSAJMQ==,type:str]
  HOMEPAGE_VAR_AUDIOBOOKSHELF_API_KEY: ENC[AES256_GCM,data:lNGmchALP3bkMVASmaCv7hu+5bvQlp9emTFedX21X0zBPfHWrzMMqWtSebutIVEgnGxEU4PAlI6QdU/exiszqqkLaDhaE6Znh9NiXMeNPRqgS2DrlV4Mg53pD8I52RdQHMCKKg213iAoniM3wgWoA1SnVKr3HLipt4iSF44c2oGe3en7HP1YAfgim2gnXw4SbOlQjBhVN57RuYjiQKPDufSTsk6L60QExND+cu2fwpRH/hYTOlWZgELfuoHmcgj6vLPhYCm1P3rx7wsdvFJS3w==,iv:7V5eygCDZeA0ELl9EXS1ItJGYt6VoGMyTR7ytT6Svcw=,tag:eJ2VlUW/Y2OgDfRWhmNF9A==,type:str]
  HOMEPAGE_VAR_PROXMOX_API_SECRET: ENC[AES256_GCM,data:lq3oYVB57iuE2Y3jwW6E4YTf2Nu2d2YF2Z7R75pjiFbvrGqR,iv:O92BhmYXWYGTsVre8LzXCO5Yy1NpB0jCSG2/Ws8zPY0=,tag:1A+0D15BvR3iXeyQGoWy1w==,type:str]
  HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:CW1bKfDM3tVVHQLcFJSZH94ja6Q=,iv:uAL5YwYUViSay6b3oPiEeSGe9vPGdf/bRCUgOUMYNKM=,tag:tVPd69IzlR/rNWBqaucCcw==,type:str]
  HOMEPAGE_VAR_UNIFI_USERNAME: ENC[AES256_GCM,data:EU0Rk0Lbo62funfMrA==,iv:iDzIMYJ72vHQuJg8RWJh4v+RBD6jUI30fsqN50KxnHI=,tag:XRiD4BPzw3F7GTleZpbfUQ==,type:str]
  HOMEPAGE_VAR_UNIFI_PASSWORD: ENC[AES256_GCM,data:AjuDOhfnVKai+/hDpfdUH7xH0P0=,iv:5cfiZH1Gdg4Pu2OlcD+wNSBhCjFfi9Or6lpuoelVJcQ=,tag:rELv3NJL7CYrNaKyf/qFug==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYzY5a1lPOFlhVU4wbUJX
        MEI0Sjl0WkNjZWtNeVd3cSs2TWkxOWtoMDBBCmpPRHBqNXVQc3RneXd5TlZlcXdU
        V1hDUjBMUC9IQWNYMU1QYjFwMXR3eTAKLS0tIEFlSWJXeVF5RzNaU1pySmI5RXlr
        Tk1BTUQzUHNMUU5zRUg3NHFoYVVITUEKeu2L2iL6/wbZZkhibL38tLsF+nXOL32z
        U3Ud0uJfira7OIQEtGwxX8N5TxFTXp4ZObN8EJmPVRaxGx5JkNUSzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T12:25:06Z"
  mac: ENC[AES256_GCM,data:w3cfTHSQsL53careueUn7yHgJ+VRB8c+tsRSl22FhploU2HTRr65u+3+6mAJXo9dyQsNYTIgXYAay6LR0MLGZtXERY+Zd0eEvjsqQbAxqu5Lh4DYmS4svyAAy1iwR1LkI4GsJmILTkasb2vtgbHH4rJ+BkQP7Lf553oQPWKmjE8=,iv:cpvbaQkObvZdRZECBsw+h+dPqdXgBRWuYBQLTD2CcGQ=,tag:YMbKgqMPwKjcmg5b9skZPg==,type:str]
  encrypted_regex: ^(stringData)$
  version: 3.11.0
