apiVersion: ENC[AES256_GCM,data:xO0=,iv:1mo1pbL3peNiRqOb/Tf0mAOrtLottx5WFPiy3fHVRN4=,tag:RM10IQt2ap36CG6TbH+aag==,type:str]
kind: ENC[AES256_GCM,data:rLGv0fJ3,iv:+DV8HsO3lqJ3b5Eo+ePennY50mwvjy49c/9w8jv1NeE=,tag:tcdxlTCulkmcbUuIBE0Rbg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:dVuvQmLUYrS9x4t6iJir1A==,iv:k3cqKx3Q+I9HI9oMbWiq8uP9XA+OZ6l4VziJqqCVbOI=,tag:fDb+Pn3N4ovcNOF4ID0PhA==,type:str]
  namespace: ENC[AES256_GCM,data:jwYSPokRq349v5jHN/A=,iv:+elNCd/L6LxP8vifTfvIkx8rqurwxRJ3wyBHdAOK4rs=,tag:/q7d+l327YFP1fDrY0+bAQ==,type:str]
type: ENC[AES256_GCM,data:UTCSkAys,iv:RffnPCR/7LTKMadxfKA8C7sNWGVMCHyzsisCBOkjqL4=,tag:xHmcel5JwwPqumIIbvZHXA==,type:str]
stringData:
  HOMEPAGE_VAR_AUTHENTIK_API_KEY: ENC[AES256_GCM,data:YT+aDuHAvE0c9yyuSAykGqKbUHtfFGVlagPG+OI3Ix8zdzGe5go7L2guCUdQJXEwXLoR7vj628k95nzF,iv:ynOHl+jVyZ0/E/iKOYnHrcb3Q/qetRdj2zJTMNfxNr4=,tag:Bed1D2L0rlB0LxWNjlx2Qw==,type:str]
  HOMEPAGE_VAR_CHANGEDETECTION_API_KEY: ENC[AES256_GCM,data:AxXwxfOzEu+sGomuGfCQLTpBH2UZJcpvE/zfyIkyhXw=,iv:2yQ1wvaRvvnX6C9636Zww8hwnPGd8r1CY5Yi1AjL+YU=,tag:m9LAByvzyonCBi7YmCHtGQ==,type:str]
  HOMEPAGE_VAR_AUDIOBOOKSHELF_API_KEY: ENC[AES256_GCM,data:soYE/0R+EJ6KlJFSsX6kmiWSecMIYVwTZvjhtnMw/KlTHMsR5FV0CEALGNjeoKzE4e8xvWKvTJ5Ruqeih0j7yNuTrnw89PRA/fj3yzcSXXHiPV2zy5f2SrbBqDpXchy/GnrEIEoZZkveueo05QOx9VKsPCcawL/x0S92OfcQxrlNRCUHVf4t6Y5bZC7uQzYU2i9VdUvC2KLckWZ2Fe4EUhlh/5QlCyQ2ZJ2ca2VVPOXp4hHoDuoEnXPwg85M52xMjqKJRJwNB+ZVl/RCI3U9UA==,iv:wPOc9iYehKrLjHbO8+u7VTWIXtGOhKH6E7sWlKhZnvE=,tag:nqc6xj+L+hqKpdp8OEbIWQ==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQWxkWjRYdU1Kck04UVB0
        N2tielh2ckNOZUNDOFhKMGpBT1BFTXFZQ0NnClJHT1NjUXFTcG9iK0NXME5nTVUz
        azd2MHorS3JmN3I5VTBLeUF2Y1Q5RGcKLS0tIGk1ek4vZUV2S3pMK0JuWDlTd1Jz
        WU1jMkVjQ1ppclZMRm1HZFF1ZnNPZzAKYxGQ1grWXD01U5rQQKaGTAjKtEgj+M/W
        mN/LwsGGJXDoG6jMtf14afIX0lglX/cByxqeUU5dAZ3tCIg2RG2eiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T11:22:58Z"
  mac: ENC[AES256_GCM,data:VXV71phPN1H3YgtCibLCp62FuG3Os2g+yQFi5qxFZqpKqZsbPcTPX0ieV3Fomew4DzGiu59ckJMlPIoVuKt6UJHsOgO//MlfUsKi4gC1kHsO4dQ/e0VJPsJNEhksMSKljSoplJ1JuQYZPldaViI8JBOq/V0fXQrQuBKLJEEEsiM=,iv:AHzivyWwcIKu+ho7/cKfMZdVnJmvWswvAHfeNErzvbw=,tag:f5jDYHma020xBRbO/4dG2g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
