apiVersion: v1
kind: Secret
metadata:
  name: private-apps-auth
  namespace: flux-system
  labels:
    app.kubernetes.io/name: private-apps-auth
    app.kubernetes.io/instance: private-apps-auth-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
type: Opaque
stringData:
  identity: ENC[AES256_GCM,data:mVsox2MvRmB0N5NYQQxnpfeEGHQJtxyt4JLpLhIUXQTEXtHcjb7f8N3vRXrnpP8wOevwHl7yIWxns9xM7bMjxlWppzgsQAP/8R5729nqmkrZ7zc1IB7ysO+YDhiitri8frEu6n5MUT8lI3/bbZcWwbCnufNAgMbp0Q+Sdp0K9rIaYauKvgGTqBGvfnizwvpIIv8UJhTztyk0nojqKpuymm2Na75o4xzxIJZUHKnT9k+I4EEkaqs8G0AUaAR+IqzZVp77DEhx4oyAD0wGK4KIxpYlxf0C4oRewlw8/qEuXtjpKnVwKEO77F8V1hsDlZHJ+wp34tRdqrotKk0KBXQJCa2dnb/KKmYpUZRJ+uIN+eIqrDwpnacpRyiAVIAemPbSZI0J74dULvv9cBKbPtSIMpmJnXLfi3yFSc2ZnmWfx3+9OvAvZMcNu/PUqV0vc04gXkGtPCzXMPOxELEPT3M2W3VaK4XYm71QMAH6E/bVFHySHm30/8h/A9DbU992Bb2iu9xmFmP8pnZAbSVyGedY5dEthyuvPw8Cg01O,iv:7hU1Vxw8OPH8fWxs8VRmk1lRFwuZGpdVa9LQlKoklrg=,tag:+t2qBPKhmY00Ufb6lx5lXA==,type:str]
  identity.pub: ENC[AES256_GCM,data:S6EoPqSZfFL2UpAj93qCpgtfR/Sun8y13MCdL0GcWiM0zu6MBGFzuNr1TjKrZkOKohJZ9EznEk20npSRYm5kDYn35BGbilZfvYYOFvda31PWN5RhY/z9VfiaIoKIxsYZX+M=,iv:W3JjKZjTMda0t8bIEIKNhojrgXxY44wGVjbKQFf9oBY=,tag:2LNQUK4OAEN/l3yHvKEH1Q==,type:str]
  known_hosts: ENC[AES256_GCM,data:KRwAhbB4EQfbowaoZ3lO8gMEb5BHABnMnAY10ETnAOIUIOVR3JjMIr6WY5EAw3svj1S/Z4678DKE7o0pyhVitscp3yc1OmYn6XItDsrX74CXEougiOHFJMvBowXON0tJuv+RF0r2vgJylf8iseF29sN3asM1N+/5T/96w76LwzlpquMMAJ9TZa+ik5+9RdMMW5IIs5IOUmmLieJaFTHqOdYIl7HIqUxf5JmH,iv:Li5NVzlKlvErETihovRqKTUrD8U1AKmKo6MaSfS4zSY=,tag:tPnEVA/rzOVWCWmwDhYAZQ==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SHkzTndESDk3WU1wTWNk
        Nms4WmdmOWo0bHFidFhXYVBJT0hzeHNqUVNNCkJCRnNsSCszM1gwNHAyRlh4SmxE
        NnZINkU4cENIdTZ5d3V6akZVZWMwWU0KLS0tIHNEa1REcFFTTDBPQ1dXaVNSZDRz
        OVVTZ1Vtbm5YT2pJVFFaamZFdnRHOWMK7C4thUWhplBhZP9zxC9uSQ1v9RLO2EJN
        7oiFxzAZN46NQ5AmU8MDdChV7TlRawNZGFNj3yoh/SsajyxdJ15MxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T12:12:42Z"
  mac: ENC[AES256_GCM,data:C4JyL5LQRso0AS+QiAc3nJMLwT7Y4GMge+dpBJEt4zBU5P+YsGAWw/nlln/1XFmC35eJ/bXz0dndSJY322VnlCZiXuscCQoRoKhY3X+ZpCKpttViWjyn+4U3Dswk4Ves+9t1XQbt1toTpoXMWcsG1EmPptZyCY8Dx3LL1rtuVlc=,iv:MdpDh/FOPfjZEj6s/r+Ev5DkRM03kxIl7n2AqK/5OjI=,tag:s1z+u4pBAvUxvlsIVmaPrQ==,type:str]
  encrypted_regex: ^(stringData)$
  version: 3.11.0
